name = "NormalizeDict"
uuid = "8a7d223a-a7dc-4abf-8bc1-b0ce2ace9adc"
authors = ["Micah Rufsvold <mrufsvold@mathematica-mpr.com>"]
version = "0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
