name = "Normalize"
uuid = "8a7d223a-a7dc-4abf-8bc1-b0ce2ace9adc"
authors = ["Micah Rufsvold <mjrufsvold@protonmail.com>"]
version = "0.1.0"

[deps]
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
PooledArrays = "1.4"
StructTypes = "1.10"
