name = "NormalizeDict"
uuid = "8a7d223a-a7dc-4abf-8bc1-b0ce2ace9adc"
authors = ["Micah Rufsvold <mrufsvold@mathematica-mpr.com>"]
version = "0.1.0"

[deps]
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
